"use strict";

const { pool, withTransaction } = require("../db");
const schedulingScoreProvider = require("./schedulingScoreProvider");
const { createWorkdayAuditLog } = require("./schedulingAuditService");
const { requireActiveMembership } = require("./staffSchedulingService");

const ACTIVE_DAY_STATUSES = new Set(["DRAFT", "PENDING", "APPROVED", "ADJUSTED"]);
const MANAGER_ROLES = new Set(["owner", "admin", "manager"]);
const OWNER_ADMIN_ROLES = new Set(["owner", "admin"]);

function httpError(message, statusCode = 400, code = "INVALID_REQUEST", details) {
  const error = new Error(message); error.statusCode = statusCode; error.code = code; if (details) error.details = details; return error;
}
function isoDate(value) { const date = String(value || "").slice(0, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw httpError("日期格式不正確"); return date; }
function mondayOf(dateValue) { const date = new Date(`${isoDate(dateValue)}T00:00:00Z`); const weekday = date.getUTCDay(); date.setUTCDate(date.getUTCDate() - ((weekday + 6) % 7)); return date.toISOString().slice(0, 10); }
function uniqueActiveDates(rows) { return [...new Set((rows || []).filter((row) => ACTIVE_DAY_STATUSES.has(row.status)).map((row) => isoDate(row.workDate || row.work_date)))].sort(); }
function assertWeeklyLimit({ dates, attemptedDate, maxSelectableDays, tierName, scoreStatus }) {
  const attempted = isoDate(attemptedDate), weekStart = mondayOf(attempted);
  const selectedDays = [...new Set((dates || []).map(isoDate).filter((date) => mondayOf(date) === weekStart))].sort();
  if (selectedDays.length > Number(maxSelectableDays)) throw httpError("已超過本週可選工作日上限", 409, "WEEKLY_SELECTION_LIMIT_EXCEEDED", {
    weekStart, attemptedDate: attempted, existingDays: selectedDays.filter((date) => date !== attempted), selectedDays,
    totalDays: selectedDays.length, maxSelectableDays: Number(maxSelectableDays), tierName, scoreStatus
  });
  return selectedDays;
}
function capacityFor(calendar) { return Number(calendar.maxRequestCapacity ?? calendar.requiredHeadcount ?? 0); }
function deadlinePassed(calendar) { if (!calendar.requestDeadlineAt) return false; const raw=String(calendar.requestDeadlineAt).replace(" ","T"); return new Date(raw.endsWith("Z") || raw.includes("+") ? raw : raw + "+08:00") < new Date(); }
function reservedCapacity(calendar) { return Number(calendar.approvedHeadcount || 0) + (calendar.pendingReservesCapacity ? Number(calendar.pendingRequestCount || 0) : 0); }
function publicEmployeeDay(calendar, ownStatus = null) {
  const capacity = capacityFor(calendar), approved = Number(calendar.approvedHeadcount || 0), pending = Number(calendar.pendingRequestCount || 0);
  return { workDate: isoDate(calendar.workDate || calendar.businessDate), requiredHeadcount: Number(calendar.requiredHeadcount || 0), maxRequestCapacity: capacity,
    approvedHeadcount: approved, pendingRequestCount: pending, availableSlots: Math.max(0, capacity - (calendar.pendingReservesCapacity ? pending : approved)), ownStatus,
    isOpen: Boolean(calendar.isOpen), isLocked: Boolean(calendar.requestLocked), deadline: calendar.requestDeadlineAt || null };
}
async function role(connection, storeId, actorId, allowed) { const membership = await requireActiveMembership(connection, storeId, actorId); if (!allowed.has(String(membership.storeRole || "").toLowerCase())) throw httpError("權限不足", 403, "SCHEDULING_PERMISSION_REQUIRED"); return membership; }
async function requireOwnerAdmin(connection, storeId, actorId) { return role(connection, storeId, actorId, OWNER_ADMIN_ROLES); }
async function requireManager(connection, storeId, actorId) { return role(connection, storeId, actorId, MANAGER_ROLES); }
async function periodForDate(connection, storeId, periodId, date, lock = false) { const [rows] = await connection.query(`SELECT * FROM staff_schedule_periods WHERE id=? AND store_id=? AND ? BETWEEN starts_on AND ends_on ${lock ? "FOR UPDATE" : ""}`, [periodId, storeId, date]); if (!rows[0]) throw httpError("日期不在排班期間內", 404, "SCHEDULE_PERIOD_NOT_FOUND"); return rows[0]; }
async function getCalendarRows(connection, storeId, actorId, month, admin = false) {
  await requireActiveMembership(connection, storeId, actorId); const first = `${String(month).slice(0, 7)}-01`;
  const [rows] = await connection.query(`SELECT DATE_FORMAT(bc.business_date,'%Y-%m-%d') workDate,bc.is_open isOpen,bc.required_headcount requiredHeadcount,
    bc.max_request_capacity maxRequestCapacity,bc.request_locked requestLocked,bc.request_deadline_at requestDeadlineAt,bc.pending_reserves_capacity pendingReservesCapacity,bc.version,
    COUNT(DISTINCT CASE WHEN d.status IN ('APPROVED','ADJUSTED') THEN d.staff_user_id END) approvedHeadcount,
    COUNT(DISTINCT CASE WHEN d.status='PENDING' THEN d.staff_user_id END) pendingRequestCount
    ${admin ? ",GROUP_CONCAT(DISTINCT CASE WHEN d.status IN ('APPROVED','ADJUSTED') THEN su.display_name END ORDER BY su.display_name) approvedNames" : ""}
    FROM store_business_calendars bc LEFT JOIN (SELECT rd.*,r.staff_user_id FROM staff_workday_request_days rd JOIN staff_workday_requests r ON r.id=rd.request_id AND r.store_id=rd.store_id) d ON d.store_id=bc.store_id AND d.work_date=bc.business_date
    ${admin ? "LEFT JOIN staff_users su ON su.id=d.staff_user_id" : ""} WHERE bc.store_id=? AND bc.business_date>=DATE_SUB(?,INTERVAL WEEKDAY(?) DAY) AND bc.business_date<DATE_ADD(LAST_DAY(?),INTERVAL 7 DAY) GROUP BY bc.id ORDER BY bc.business_date`, [storeId, first, first, first]);
  return rows;
}
async function getEmployeeWorkdayCalendar(storeId, actorId, query) { const rows = await getCalendarRows(pool, storeId, actorId, query.month, false); const [own] = await pool.query(`SELECT DATE_FORMAT(d.work_date,'%Y-%m-%d') workDate,d.status FROM staff_workday_request_days d JOIN staff_workday_requests r ON r.id=d.request_id AND r.store_id=d.store_id WHERE d.store_id=? AND r.staff_user_id=? AND d.work_date BETWEEN ? AND ?`, [storeId, actorId, rows[0]?.workDate || "1900-01-01", rows.at(-1)?.workDate || "1900-01-01"]); const statuses = new Map(own.map((row) => [row.workDate, row.status])); return { month: String(query.month).slice(0,7), days: rows.map((row) => publicEmployeeDay(row, statuses.get(row.workDate) || null)) }; }
async function getEmployeeWorkdaySummary(storeId, actorId, query) { await requireActiveMembership(pool, storeId, actorId); const score = await schedulingScoreProvider.getLatestSchedulingScore({ connection: pool, storeId, staffUserId: actorId, effectiveDate: query.effectiveDate }); const [rows] = await pool.query(`SELECT r.id,r.status,r.version,COUNT(CASE WHEN d.status IN ('DRAFT','PENDING','APPROVED','ADJUSTED') THEN 1 END) selectedCount FROM staff_workday_requests r LEFT JOIN staff_workday_request_days d ON d.request_id=r.id AND d.store_id=r.store_id WHERE r.store_id=? AND r.period_id=? AND r.staff_user_id=? GROUP BY r.id`, [storeId, query.periodId, actorId]); return { request: rows[0] || null, score, scoreDisplay: score.status === "INSUFFICIENT_DATA" ? "分數資料不足" : score.tierName }; }
async function validateDatePolicy(connection, storeId, date, approving = false) { const [rows] = await connection.query(`SELECT bc.*,COUNT(DISTINCT CASE WHEN d.status IN ('APPROVED','ADJUSTED') THEN r.staff_user_id END) approvedHeadcount FROM store_business_calendars bc LEFT JOIN staff_workday_request_days d ON d.store_id=bc.store_id AND d.work_date=bc.business_date LEFT JOIN staff_workday_requests r ON r.id=d.request_id AND r.store_id=d.store_id WHERE bc.store_id=? AND bc.business_date=? GROUP BY bc.id FOR UPDATE`, [storeId,date]); const calendar=rows[0]; if (!calendar || !calendar.is_open) throw httpError("此日為店休日",409,"STORE_CLOSED"); if (calendar.request_locked) throw httpError("此日已鎖定",409,"DATE_LOCKED"); if (deadlinePassed(calendar)) throw httpError("申請期限已過",409,"REQUEST_DEADLINE_PASSED"); if (approving && reservedCapacity(calendar)>=capacityFor(calendar)) throw httpError("此日核准名額已滿",409,"DATE_CAPACITY_FULL"); return calendar; }
async function saveEmployeeWorkdayDraft(storeId, actorId, input) { return withTransaction(async (connection) => { await requireActiveMembership(connection,storeId,actorId,true); const dates=[...new Set((input.dates||[]).map(isoDate))].sort(); if(!dates.length) throw httpError("請至少選擇一個工作日"); for(const date of dates){await periodForDate(connection,storeId,input.periodId,date,true);await validateDatePolicy(connection,storeId,date);} const score=await schedulingScoreProvider.getLatestSchedulingScore({connection,storeId,staffUserId:actorId,effectiveDate:dates[0]}); const [existing]=await connection.query(`SELECT DATE_FORMAT(d.work_date,'%Y-%m-%d') workDate,d.status FROM staff_workday_request_days d JOIN staff_workday_requests r ON r.id=d.request_id AND r.store_id=d.store_id WHERE r.store_id=? AND r.staff_user_id=? AND d.status IN ('PENDING','APPROVED','ADJUSTED') AND (d.requested_source <> 'ADMIN' OR COALESCE((SELECT bc.admin_assignment_counts_toward_limit FROM store_business_calendars bc WHERE bc.store_id=d.store_id AND bc.business_date=d.work_date),1)=1) AND d.work_date BETWEEN DATE_SUB(?,INTERVAL WEEKDAY(?) DAY) AND DATE_ADD(?,INTERVAL 6-WEEKDAY(?) DAY)`,[storeId,actorId,dates[0],dates[0],dates.at(-1),dates.at(-1)]); const all=[...new Set([...uniqueActiveDates(existing),...dates])]; for(const date of dates)assertWeeklyLimit({dates:all,attemptedDate:date,maxSelectableDays:score.maxSelectableDays,tierName:score.tierName,scoreStatus:score.status}); const [requests]=await connection.query("SELECT * FROM staff_workday_requests WHERE store_id=? AND period_id=? AND staff_user_id=? FOR UPDATE",[storeId,input.periodId,actorId]); let request=requests[0]; if(request&&Number(input.version)!==Number(request.version))throw httpError("資料已被更新",409,"VERSION_CONFLICT"); if(!request){const [created]=await connection.query("INSERT INTO staff_workday_requests(store_id,period_id,staff_user_id,status) VALUES (?,?,?,'DRAFT')",[storeId,input.periodId,actorId]);request={id:created.insertId,version:1};} else if(request.status!=="DRAFT") throw httpError("已送出的申請不可覆寫",409,"REQUEST_ALREADY_SUBMITTED"); await connection.query("DELETE FROM staff_workday_request_days WHERE store_id=? AND request_id=? AND status='DRAFT'",[storeId,request.id]); for(const date of dates)await connection.query("INSERT INTO staff_workday_request_days(store_id,request_id,work_date,status,requested_source) VALUES (?,?,?,'DRAFT','EMPLOYEE') ON DUPLICATE KEY UPDATE status=IF(status='DRAFT','DRAFT',status)",[storeId,request.id,date]); await connection.query("UPDATE staff_workday_requests SET version=version+1 WHERE id=? AND store_id=?",[request.id,storeId]); return {id:request.id,status:"DRAFT",version:Number(request.version)+1,dates}; }); }
async function submitEmployeeWorkdayRequest(storeId,actorId,input){return withTransaction(async(connection)=>{await requireActiveMembership(connection,storeId,actorId,true);const [rows]=await connection.query("SELECT * FROM staff_workday_requests WHERE id=? AND store_id=? AND staff_user_id=? FOR UPDATE",[input.requestId,storeId,actorId]);const request=rows[0];if(!request)throw httpError("找不到申請",404,"REQUEST_NOT_FOUND");if(request.status==='PENDING')return{id:request.id,status:request.status,version:request.version};if(request.status!=="DRAFT")throw httpError("此申請無法送出",409,"INVALID_REQUEST_STATUS");if(Number(input.version)!==Number(request.version))throw httpError("資料已被更新",409,"VERSION_CONFLICT");await connection.query("UPDATE staff_workday_request_days SET status='PENDING' WHERE store_id=? AND request_id=? AND status='DRAFT'",[storeId,request.id]);await connection.query("UPDATE staff_workday_requests SET status='PENDING',submitted_at=NOW(),version=version+1 WHERE id=? AND store_id=?",[request.id,storeId]);await createWorkdayAuditLog(connection,{storeId,actorStaffUserId:actorId,actionType:"REQUEST_SUBMIT",entityType:"staff_workday_request",entityId:request.id,oldValue:{status:"DRAFT"},newValue:{status:"PENDING"}});return{id:request.id,status:"PENDING",version:Number(request.version)+1};});}
async function removeEmployeeWorkdayDate(storeId,actorId,date,input={}){return withTransaction(async(connection)=>{await requireActiveMembership(connection,storeId,actorId,true);const [rows]=await connection.query(`SELECT d.*,r.staff_user_id FROM staff_workday_request_days d JOIN staff_workday_requests r ON r.id=d.request_id AND r.store_id=d.store_id WHERE d.store_id=? AND r.staff_user_id=? AND d.work_date=? FOR UPDATE`,[storeId,actorId,isoDate(date)]);const day=rows[0];if(!day) return {removed:false};if(!["DRAFT","PENDING"].includes(day.status))throw httpError("已核准日期不可由員工移除",409,"APPROVED_DATE_IMMUTABLE");if(input.version!=null && Number(input.version)!==Number(day.version))throw httpError("資料已被更新",409,"VERSION_CONFLICT");await connection.query("UPDATE staff_workday_request_days SET status='CANCELLED',version=version+1 WHERE id=? AND store_id=?",[day.id,storeId]);await createWorkdayAuditLog(connection,{storeId,actorStaffUserId:actorId,actionType:"REQUEST_CANCEL",entityType:"staff_workday_request_day",entityId:day.id,oldValue:{status:day.status},newValue:{status:"CANCELLED"},reason:input.reason});return{removed:true};});}
async function listEmployeeWorkdayRequests(storeId,actorId){await requireActiveMembership(pool,storeId,actorId);const [rows]=await pool.query(`SELECT r.*,JSON_ARRAYAGG(JSON_OBJECT('date',DATE_FORMAT(d.work_date,'%Y-%m-%d'),'status',d.status)) days FROM staff_workday_requests r LEFT JOIN staff_workday_request_days d ON d.request_id=r.id AND d.store_id=r.store_id WHERE r.store_id=? AND r.staff_user_id=? GROUP BY r.id ORDER BY r.created_at DESC`,[storeId,actorId]);return rows;}
async function getAdminWorkdayCalendar(storeId,actorId,query){await requireManager(pool,storeId,actorId);return{month:String(query.month).slice(0,7),days:await getCalendarRows(pool,storeId,actorId,query.month,true)};}
async function listAdminWorkdayRequests(storeId,actorId,query={}){await requireManager(pool,storeId,actorId);const [rows]=await pool.query(`SELECT r.id,r.staff_user_id staffUserId,su.display_name displayName,r.status,r.version,r.submitted_at submittedAt,JSON_ARRAYAGG(JSON_OBJECT('id',d.id,'date',DATE_FORMAT(d.work_date,'%Y-%m-%d'),'status',d.status)) days FROM staff_workday_requests r JOIN staff_users su ON su.id=r.staff_user_id LEFT JOIN staff_workday_request_days d ON d.request_id=r.id AND d.store_id=r.store_id WHERE r.store_id=? AND (? IS NULL OR r.period_id=?) GROUP BY r.id ORDER BY r.submitted_at`,[storeId,query.periodId||null,query.periodId||null]);return rows;}
async function reviewWorkdayRequest(storeId,actorId,id,input){return withTransaction(async(connection)=>{await requireManager(connection,storeId,actorId);const status=String(input.status||"").toUpperCase();if(!["APPROVED","REJECTED","ADJUSTED"].includes(status))throw httpError("審核狀態不正確");if(status!=="APPROVED"&&!String(input.reason||"").trim())throw httpError("請填寫調整或拒絕原因");const [rows]=await connection.query("SELECT * FROM staff_workday_requests WHERE id=? AND store_id=? FOR UPDATE",[id,storeId]);const request=rows[0];if(!request)throw httpError("找不到申請",404,"REQUEST_NOT_FOUND");if(["APPROVED","REJECTED"].includes(request.status)&&request.status===status)return{id:request.id,status:request.status,version:request.version};if(!["DRAFT","PENDING"].includes(request.status))throw httpError("此申請狀態不可再審核",409,"INVALID_REQUEST_STATUS");if(Number(input.version)!==Number(request.version))throw httpError("資料已被更新",409,"VERSION_CONFLICT");const [days]=await connection.query("SELECT * FROM staff_workday_request_days WHERE store_id=? AND request_id=? AND status IN ('PENDING','DRAFT') FOR UPDATE",[storeId,id]);for(const day of days){if(status!=="REJECTED")await validateDatePolicy(connection,storeId,isoDate(day.work_date),true);await connection.query("UPDATE staff_workday_request_days SET status=?,reviewed_by=?,reviewed_at=NOW(),admin_note=?,version=version+1 WHERE id=? AND store_id=?",[status,actorId,String(input.reason||"").trim()||null,day.id,storeId]);}const header=status==="ADJUSTED"?"PARTIALLY_APPROVED":status;await connection.query("UPDATE staff_workday_requests SET status=?,reviewed_by=?,reviewed_at=NOW(),review_reason=?,version=version+1 WHERE id=? AND store_id=?",[header,actorId,String(input.reason||"").trim()||null,id,storeId]);await createWorkdayAuditLog(connection,{storeId,actorStaffUserId:actorId,actionType:status==="REJECTED"?"REQUEST_REJECT":status==="ADJUSTED"?"DATE_ADJUST":"REQUEST_APPROVE",entityType:"staff_workday_request",entityId:Number(id),oldValue:{status:request.status},newValue:{status:header},reason:input.reason});return{id:Number(id),status:header,version:Number(request.version)+1};});}
async function bulkReviewWorkdayRequests(storeId,actorId,input){const results=[];const items=[...(input.requests||[])].sort((a,b)=>Number(a.id)-Number(b.id));for(const item of items)results.push(await reviewWorkdayRequest(storeId,actorId,item.id,{...item,status:input.status,reason:input.reason}));return results;}
async function updateDateCapacity(storeId,actorId,date,input){return withTransaction(async(connection)=>{await requireOwnerAdmin(connection,storeId,actorId);if(!String(input.reason||"").trim())throw httpError("請填寫調整原因");const [rows]=await connection.query("SELECT * FROM store_business_calendars WHERE store_id=? AND business_date=? FOR UPDATE",[storeId,isoDate(date)]);const old=rows[0];if(!old)throw httpError("找不到營業日",404);if(Number(input.version)!==Number(old.version))throw httpError("資料已被更新",409,"VERSION_CONFLICT");const capacity=Number(input.maxRequestCapacity);if(!Number.isInteger(capacity)||capacity<0||capacity>100)throw httpError("申請容量不正確");await connection.query("UPDATE store_business_calendars SET max_request_capacity=?,request_locked=?,request_deadline_at=?,pending_reserves_capacity=?,admin_assignment_counts_toward_limit=?,updated_by=?,version=version+1 WHERE id=?",[capacity,input.isLocked?1:0,input.deadline||null,input.pendingReservesCapacity?1:0,input.adminAssignmentCountsTowardLimit===false?0:1,actorId,old.id]);await createWorkdayAuditLog(connection,{storeId,actorStaffUserId:actorId,actionType:input.isLocked&&!old.request_locked?"DATE_LOCK":!input.isLocked&&old.request_locked?"DATE_UNLOCK":"CAPACITY_OVERRIDE",entityType:"store_business_calendar",entityId:old.id,oldValue:old,newValue:input,reason:input.reason});return{workDate:isoDate(date),version:Number(old.version)+1};});}
async function listScoreTierRules(storeId,actorId){await requireOwnerAdmin(pool,storeId,actorId);const [rows]=await pool.query("SELECT * FROM scheduling_score_tier_rules WHERE store_id=? ORDER BY effective_from DESC,minimum_score DESC",[storeId]);return rows;}
async function saveScoreTierRules(storeId,actorId,input){return withTransaction(async(connection)=>{await requireOwnerAdmin(connection,storeId,actorId);if(!String(input.reason||"").trim())throw httpError("請填寫調整原因");const rules=input.rules||[];if(rules.filter(r=>r.isNeutralDefault&&r.isEnabled!==false).length!==1)throw httpError("每個生效區間必須恰有一個中性預設級距");for(const rule of rules){const max=Number(rule.maxSelectableDays);if(!Number.isInteger(max)||max<=0)throw httpError("每週可選天數必須大於 0");await connection.query(`INSERT INTO scheduling_score_tier_rules(store_id,tier_code,tier_name,minimum_score,max_selectable_days,effective_from,effective_to,is_neutral_default,is_enabled,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[storeId,rule.tierCode,rule.tierName,rule.minimumScore??null,max,rule.effectiveFrom,rule.effectiveTo||null,rule.isNeutralDefault?1:0,rule.isEnabled===false?0:1,actorId,actorId]);}await createWorkdayAuditLog(connection,{storeId,actorStaffUserId:actorId,actionType:"SCORE_TIER_CHANGE",entityType:"scheduling_score_tier_rules",entityId:storeId,oldValue:null,newValue:rules,reason:input.reason});return{rulesSaved:rules.length};});}
async function updateEmployeeWeeklyLimit(storeId,actorId,staffUserId,input){return withTransaction(async(connection)=>{await requireOwnerAdmin(connection,storeId,actorId);await requireActiveMembership(connection,storeId,staffUserId,true);if(!String(input.reason||"").trim())throw httpError("請填寫調整原因");const max=Number(input.maxSelectableDays);if(!Number.isInteger(max)||max<=0)throw httpError("每週可選天數必須大於 0");const [result]=await connection.query(`INSERT INTO staff_weekly_limit_overrides(store_id,staff_user_id,week_start,effective_from,effective_to,max_selectable_days,reason,created_by,updated_by,is_enabled) VALUES(?,?,?,?,?,?,?,?,?,1)`,[storeId,staffUserId,input.weekStart||null,input.effectiveFrom,input.effectiveTo,max,input.reason,actorId,actorId]);await createWorkdayAuditLog(connection,{storeId,actorStaffUserId:actorId,actionType:"WEEKLY_LIMIT_OVERRIDE",entityType:"staff_weekly_limit_override",entityId:result.insertId,oldValue:null,newValue:input,reason:input.reason});return{id:result.insertId};});}

module.exports={ACTIVE_DAY_STATUSES,mondayOf,uniqueActiveDates,assertWeeklyLimit,capacityFor,publicEmployeeDay,getEmployeeWorkdayCalendar,getEmployeeWorkdaySummary,saveEmployeeWorkdayDraft,submitEmployeeWorkdayRequest,removeEmployeeWorkdayDate,listEmployeeWorkdayRequests,getAdminWorkdayCalendar,listAdminWorkdayRequests,reviewWorkdayRequest,bulkReviewWorkdayRequests,updateDateCapacity,listScoreTierRules,saveScoreTierRules,updateEmployeeWeeklyLimit,createWorkdayAuditLog};
