"use strict";
const express = require("express");
const { authenticate, requireStoreScope, requireStoreRole } = require("../middleware/auth");
const { requireStoreFeature } = require("../middleware/storeFeature");
const service = require("../services/staffSchedulingService");
const workday = require("../services/staffWorkdayRequestService");
const router = express.Router();
const manage = requireStoreRole(["owner", "admin", "manager"]);
router.use(authenticate, requireStoreScope(), requireStoreFeature("staff_management_enabled"));
const storeId = (req) => Number(req.storeId), actorId = (req) => Number(req.user.id);
const handler = (fn) => async (req,res,next) => { try { return res.json(await fn(req)); } catch(error) { if(error.statusCode&&error.code)return res.status(error.statusCode).json({message:error.message,errorCode:error.code,...(error.details||{})});return next(error); } };
const workdayEnabled = requireStoreFeature("staff_workday_selection_enabled");
router.get("/employment-profiles", manage, handler((req) => service.listEmploymentProfiles(storeId(req),actorId(req))));
router.put("/employment-profiles/:staffUserId", manage, handler((req) => service.upsertEmploymentProfile(storeId(req),actorId(req),Number(req.params.staffUserId),req.body)));
router.get("/periods", handler((req) => service.listPeriods(storeId(req),actorId(req))));
router.post("/periods", manage, handler((req) => service.createPeriod(storeId(req),actorId(req),req.body)));
router.get("/calendar", manage, handler((req) => service.listCalendar(storeId(req),actorId(req),req.query.from,req.query.to)));
router.put("/calendar/:businessDate", manage, handler((req) => service.upsertCalendar(storeId(req),actorId(req),{...req.body,businessDate:req.params.businessDate})));
router.post("/periods/:periodId/calendar/defaults", manage, handler((req) => service.seedCalendarDefaults(storeId(req),actorId(req),Number(req.params.periodId),req.body)));
router.get("/me/availability", handler((req) => service.getAvailability(storeId(req),actorId(req),Number(req.query.periodId))));
router.put("/me/availability/:periodId", handler((req) => service.saveAvailability(storeId(req),actorId(req),Number(req.params.periodId),req.body,false)));
router.post("/me/availability/:periodId/submit", handler((req) => service.saveAvailability(storeId(req),actorId(req),Number(req.params.periodId),req.body,true)));
router.get("/time-off", handler((req) => service.listTimeOff(storeId(req),actorId(req))));
router.post("/me/time-off", handler((req) => service.createTimeOff(storeId(req),actorId(req),req.body)));
router.patch("/time-off/:id/review", manage, handler((req) => service.reviewTimeOff(storeId(req),actorId(req),Number(req.params.id),req.body)));
router.post("/periods/:periodId/revisions", manage, handler((req) => service.createRevision(storeId(req),actorId(req),Number(req.params.periodId),req.body)));
router.get("/revisions/:revisionId", manage, handler((req) => service.getDraft(storeId(req),actorId(req),Number(req.params.revisionId))));
router.post("/revisions/:revisionId/shifts", manage, handler((req) => service.createShift(storeId(req),actorId(req),Number(req.params.revisionId),req.body)));
router.post("/shifts/:shiftId/assignments", manage, handler((req) => service.assignShift(storeId(req),actorId(req),Number(req.params.shiftId),req.body)));
router.get("/me/workday-calendar", workdayEnabled, handler((req) => workday.getEmployeeWorkdayCalendar(storeId(req),actorId(req),req.query)));
router.get("/me/workday-summary", workdayEnabled, handler((req) => workday.getEmployeeWorkdaySummary(storeId(req),actorId(req),req.query)));
router.put("/me/workday-selection", workdayEnabled, handler((req) => workday.saveEmployeeWorkdayDraft(storeId(req),actorId(req),req.body)));
router.post("/me/workday-selection/submit", workdayEnabled, handler((req) => workday.submitEmployeeWorkdayRequest(storeId(req),actorId(req),req.body)));
router.delete("/me/workday-selection/:date", workdayEnabled, handler((req) => workday.removeEmployeeWorkdayDate(storeId(req),actorId(req),req.params.date,req.body)));
router.get("/me/workday-requests", workdayEnabled, handler((req) => workday.listEmployeeWorkdayRequests(storeId(req),actorId(req))));
router.get("/admin/workday-calendar", workdayEnabled, manage, handler((req) => workday.getAdminWorkdayCalendar(storeId(req),actorId(req),req.query)));
router.get("/admin/workday-requests", workdayEnabled, manage, handler((req) => workday.listAdminWorkdayRequests(storeId(req),actorId(req),req.query)));
router.patch("/admin/workday-requests/:id/review", workdayEnabled, manage, handler((req) => workday.reviewWorkdayRequest(storeId(req),actorId(req),Number(req.params.id),req.body)));
router.post("/admin/workday-requests/bulk-review", workdayEnabled, manage, handler((req) => workday.bulkReviewWorkdayRequests(storeId(req),actorId(req),req.body)));
router.put("/admin/capacity/:date", workdayEnabled, manage, handler((req) => workday.updateDateCapacity(storeId(req),actorId(req),req.params.date,req.body)));
router.get("/admin/score-tier-rules", workdayEnabled, handler((req) => workday.listScoreTierRules(storeId(req),actorId(req))));
router.put("/admin/score-tier-rules", workdayEnabled, manage, handler((req) => workday.saveScoreTierRules(storeId(req),actorId(req),req.body)));
router.put("/admin/staff/:staffUserId/weekly-limit", workdayEnabled, manage, handler((req) => workday.updateEmployeeWeeklyLimit(storeId(req),actorId(req),Number(req.params.staffUserId),req.body)));
module.exports = router;
