CREATE TABLE IF NOT EXISTS store_cash_reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NULL,
  store_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  count_1000 INT NOT NULL DEFAULT 0,
  count_100 INT NOT NULL DEFAULT 0,
  count_50 INT NOT NULL DEFAULT 0,
  count_10 INT NOT NULL DEFAULT 0,
  count_1 INT NOT NULL DEFAULT 0,
  operating_cash_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  order_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  reservation_deposit_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  cash_receivable_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  same_day_full_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_cash_inflow DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  note TEXT NULL,
  created_by_staff_user_id BIGINT NULL,
  updated_by_staff_user_id BIGINT NULL,
  late_edit_approved_by_staff_user_id BIGINT NULL,
  late_edit_approved_at DATETIME NULL,
  late_edit_reason TEXT NULL,
  edit_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_store_cash_reports_store_date (store_id, report_date),
  KEY idx_store_cash_reports_company_date (company_id, report_date),
  KEY idx_store_cash_reports_store_date (store_id, report_date),
  KEY idx_store_cash_reports_created_by (created_by_staff_user_id, created_at),
  KEY idx_store_cash_reports_updated_by (updated_by_staff_user_id, updated_at)
);

CREATE TABLE IF NOT EXISTS store_cash_report_edit_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  cash_report_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  edited_by_staff_user_id BIGINT NOT NULL,
  approved_by_staff_user_id BIGINT NULL,
  edit_type ENUM('WITHIN_1_HOUR','PASSWORD_APPROVED') NOT NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  reason TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_cash_report_edit_logs_report (cash_report_id, created_at),
  KEY idx_cash_report_edit_logs_store_date (store_id, report_date),
  KEY idx_cash_report_edit_logs_edited_by (edited_by_staff_user_id, created_at)
);
