CREATE TABLE IF NOT EXISTS staff_kpi_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NULL,
  store_id BIGINT NULL,
  staff_user_id BIGINT NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  ref_type VARCHAR(100) NULL,
  ref_id BIGINT NULL,
  title VARCHAR(255) NOT NULL,
  score DECIMAL(8,2) NOT NULL DEFAULT 0,
  occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  due_at DATETIME NULL,
  completed_at DATETIME NULL,
  is_late TINYINT(1) NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_staff_kpi_event_once (event_type, ref_type, ref_id, staff_user_id),
  KEY idx_staff_kpi_events_staff_occurred (staff_user_id, occurred_at),
  KEY idx_staff_kpi_events_store_occurred (store_id, occurred_at),
  KEY idx_staff_kpi_events_company_occurred (company_id, occurred_at),
  KEY idx_staff_kpi_events_event_type (event_type),
  KEY idx_staff_kpi_events_ref (ref_type, ref_id),
  KEY idx_staff_kpi_events_is_late (is_late)
);
