CREATE TABLE IF NOT EXISTS staff_notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NULL,
  store_id BIGINT NULL,
  staff_user_id BIGINT NULL,
  type VARCHAR(80) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NULL,
  target_url VARCHAR(500) NULL,
  ref_type VARCHAR(80) NULL,
  ref_id BIGINT NULL,
  priority ENUM('LOW','NORMAL','IMPORTANT','URGENT') NOT NULL DEFAULT 'NORMAL',
  status ENUM('UNREAD','READ','DONE','DISMISSED','SNOOZED') NOT NULL DEFAULT 'UNREAD',
  due_at DATETIME NULL,
  snoozed_until DATETIME NULL,
  read_at DATETIME NULL,
  done_at DATETIME NULL,
  dismissed_at DATETIME NULL,
  read_by_staff_user_id BIGINT NULL,
  done_by_staff_user_id BIGINT NULL,
  dismissed_by_staff_user_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_staff_notifications_store_status_created (store_id, status, created_at),
  KEY idx_staff_notifications_staff_status_created (staff_user_id, status, created_at),
  KEY idx_staff_notifications_company_status_created (company_id, status, created_at),
  KEY idx_staff_notifications_ref (ref_type, ref_id),
  KEY idx_staff_notifications_due (due_at),
  KEY idx_staff_notifications_snoozed (snoozed_until)
);
