CREATE TABLE supplier_returns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  return_no VARCHAR(64) NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_store_id BIGINT UNSIGNED NULL,
  owner_company_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  return_date DATE NULL,
  submitted_at DATETIME NULL,
  approved_at DATETIME NULL,
  shipped_at DATETIME NULL,
  received_by_supplier_at DATETIME NULL,
  settled_at DATETIME NULL,
  canceled_at DATETIME NULL,
  created_by_staff_user_id BIGINT UNSIGNED NULL,
  approved_by_staff_user_id BIGINT UNSIGNED NULL,
  settled_by_staff_user_id BIGINT UNSIGNED NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_supplier_returns_return_no (return_no),
  KEY idx_supplier_returns_owner_status (owner_type, owner_store_id, owner_company_id, status),
  KEY idx_supplier_returns_supplier_status (supplier_id, status),
  KEY idx_supplier_returns_return_date (return_date),
  KEY idx_supplier_returns_created (created_at),
  CONSTRAINT fk_supplier_returns_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
  CONSTRAINT fk_supplier_returns_owner_store FOREIGN KEY (owner_store_id) REFERENCES stores(id),
  CONSTRAINT fk_supplier_returns_owner_company FOREIGN KEY (owner_company_id) REFERENCES companies(id),
  CONSTRAINT fk_supplier_returns_created_by FOREIGN KEY (created_by_staff_user_id) REFERENCES staff_users(id),
  CONSTRAINT fk_supplier_returns_approved_by FOREIGN KEY (approved_by_staff_user_id) REFERENCES staff_users(id),
  CONSTRAINT fk_supplier_returns_settled_by FOREIGN KEY (settled_by_staff_user_id) REFERENCES staff_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE supplier_return_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  return_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(128) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  line_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  reason TEXT NULL,
  photo_url TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  inventory_movement_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_supplier_return_items_return (return_id),
  KEY idx_supplier_return_items_product (product_id),
  KEY idx_supplier_return_items_sku (sku),
  KEY idx_supplier_return_items_status (status),
  CONSTRAINT fk_supplier_return_items_return FOREIGN KEY (return_id) REFERENCES supplier_returns(id),
  CONSTRAINT fk_supplier_return_items_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_supplier_return_items_movement FOREIGN KEY (inventory_movement_id) REFERENCES inventory_movements(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
