CREATE TABLE IF NOT EXISTS store_visit_records (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NULL,
  store_id BIGINT NOT NULL,
  visit_date DATE NOT NULL,
  visit_time TIME NULL,
  visited_at DATETIME NULL,
  visitor_count INT NOT NULL DEFAULT 1,
  customer_name VARCHAR(120) NULL,
  customer_phone VARCHAR(40) NULL,
  line_friend_added TINYINT(1) NOT NULL DEFAULT 0,
  line_identifier VARCHAR(255) NULL,
  line_display_name VARCHAR(255) NULL,
  interested_vehicle VARCHAR(255) NULL,
  interested_product_id BIGINT NULL,
  interested_product_sku VARCHAR(120) NULL,
  visit_result ENUM('INTERESTED','TEST_RIDE','QUOTE_REQUESTED','RESERVED','PURCHASED','NEED_FOLLOW_UP','NO_PURCHASE','OTHER') NOT NULL DEFAULT 'INTERESTED',
  follow_up_required TINYINT(1) NOT NULL DEFAULT 0,
  follow_up_at DATETIME NULL,
  note TEXT NULL,
  created_by_staff_user_id BIGINT NULL,
  updated_by_staff_user_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_store_visit_records_store_date (store_id, visit_date),
  INDEX idx_store_visit_records_company_date (company_id, visit_date),
  INDEX idx_store_visit_records_created_by (created_by_staff_user_id, created_at),
  INDEX idx_store_visit_records_updated_by (updated_by_staff_user_id, updated_at),
  INDEX idx_store_visit_records_phone (customer_phone),
  INDEX idx_store_visit_records_line_friend (line_friend_added, visit_date),
  INDEX idx_store_visit_records_result (visit_result, visit_date),
  INDEX idx_store_visit_records_followup (follow_up_required, follow_up_at)
);
