CREATE TABLE IF NOT EXISTS daily_staff_tasks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NULL,
  store_id BIGINT NULL,
  store_type VARCHAR(50) NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  category VARCHAR(80) NOT NULL DEFAULT 'GENERAL',
  due_time TIME NULL,
  repeat_rule VARCHAR(80) NOT NULL DEFAULT 'DAILY',
  priority ENUM('LOW','NORMAL','IMPORTANT','URGENT') NOT NULL DEFAULT 'NORMAL',
  is_required TINYINT(1) NOT NULL DEFAULT 1,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_daily_staff_tasks_store_enabled (store_id, enabled),
  KEY idx_daily_staff_tasks_company_enabled (company_id, enabled),
  KEY idx_daily_staff_tasks_store_type_enabled (store_type, enabled),
  KEY idx_daily_staff_tasks_due_time (due_time),
  KEY idx_daily_staff_tasks_category (category)
);

CREATE TABLE IF NOT EXISTS staff_task_instances (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id BIGINT NOT NULL,
  company_id BIGINT NULL,
  store_id BIGINT NOT NULL,
  task_date DATE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  category VARCHAR(80) NOT NULL DEFAULT 'GENERAL',
  due_at DATETIME NULL,
  priority ENUM('LOW','NORMAL','IMPORTANT','URGENT') NOT NULL DEFAULT 'NORMAL',
  status ENUM('PENDING','DONE','SKIPPED') NOT NULL DEFAULT 'PENDING',
  completed_by_staff_user_id BIGINT NULL,
  completed_at DATETIME NULL,
  skipped_by_staff_user_id BIGINT NULL,
  skipped_at DATETIME NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_staff_task_instances_task_store_date (task_id, store_id, task_date),
  KEY idx_staff_task_instances_store_date_status (store_id, task_date, status),
  KEY idx_staff_task_instances_company_date_status (company_id, task_date, status),
  KEY idx_staff_task_instances_due_at_status (due_at, status),
  KEY idx_staff_task_instances_completed_by (completed_by_staff_user_id, completed_at)
);
