import { useEffect, useState } from "react";
import { getStoredUser } from "../lib/auth";
import { schedulingApi } from "../lib/staffSchedulingApi";
import { useStoreFeatures } from "../hooks/useStoreFeatures";
import WorkdaySelectionPanel from "../components/scheduling/WorkdaySelectionPanel";
const friendlyError = (error, fallback) => !error?.message || error.message === "Not Found" ? fallback : error.message;
const tabs=["我的工作日","我的可排班時間","休假申請","排班草稿","僱用資料"];
const box={background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16,marginBottom:16};
const field={padding:"10px 12px",border:"1px solid #d1d5db",borderRadius:8,minWidth:140};
const button={padding:"10px 14px",border:0,borderRadius:8,background:"#2563eb",color:"#fff",fontWeight:700,cursor:"pointer"};
const labels={DRAFT:"草稿",SUBMITTED:"已提交",PENDING:"待審核",APPROVED:"已核准",REJECTED:"已拒絕",CANCELLED:"已取消",FULL_TIME:"全職",PART_TIME:"兼職",CONTRACT:"契約",TEMPORARY:"臨時"};

export default function StaffSchedulingPage(){
 const { features }=useStoreFeatures();
 const user=getStoredUser(); const storeRole=String(user?.storeRole||user?.store_role||"").toLowerCase(); const manager=storeRole?["owner","admin","manager"].includes(storeRole):["ADMIN","MANAGER"].includes(String(user?.role||"").toUpperCase());
 const [tab,setTab]=useState(tabs[1]),[periods,setPeriods]=useState([]),[periodId,setPeriodId]=useState(""),[profiles,setProfiles]=useState([]),[timeOff,setTimeOff]=useState([]),[availability,setAvailability]=useState(null),[draft,setDraft]=useState(null),[message,setMessage]=useState(""),[loadErrors,setLoadErrors]=useState({});
 const [windowForm,setWindowForm]=useState({specificDate:"",startsAt:"10:00",endsAt:"19:00",preference:"AVAILABLE",note:""});
 const [leave,setLeave]=useState({leaveType:"PERSONAL",startsAt:"",endsAt:"",publicNote:"",privateReason:""});
 const [periodForm,setPeriodForm]=useState({name:"",startsOn:"",endsOn:"",inputDeadlineAt:"",timezone:"Asia/Taipei"});
 const [shiftForm,setShiftForm]=useState({shiftDate:"",startsAt:"10:00",endsAt:"19:00",requiredHeadcount:1,requiredRole:""}),[selectedStaff,setSelectedStaff]=useState("");
 const run=async(fn,ok)=>{try{setMessage("");const result=await fn();if(ok)setMessage(ok);return result}catch(e){setMessage(friendlyError(e,"操作失敗，請稍後再試"));return null}};
 const load=async()=>{const requests=[schedulingApi.periods(),schedulingApi.timeOff(),...(manager?[schedulingApi.profiles()]:[])];const [periodResult,timeOffResult,profileResult]=await Promise.allSettled(requests);const errors={};if(periodResult.status==="fulfilled"){const p=periodResult.value||[];setPeriods(p);if(!periodId&&p[0])setPeriodId(String(p[0].id));}else{errors.periods=friendlyError(periodResult.reason,"無法載入排班期間");}if(timeOffResult.status==="fulfilled")setTimeOff(timeOffResult.value||[]);else errors.timeOff=friendlyError(timeOffResult.reason,"無法載入休假申請");if(manager&&profileResult?.status==="fulfilled")setProfiles(profileResult.value||[]);else if(manager&&profileResult?.status==="rejected")errors.profiles=friendlyError(profileResult.reason,"無法載入員工僱用資料");setLoadErrors(errors);};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(periodId)schedulingApi.availability(periodId).then((value)=>{setAvailability(value);setLoadErrors((current)=>({...current,availability:""}));}).catch((error)=>{setAvailability(null);setLoadErrors((current)=>({...current,availability:friendlyError(error,"無法載入可排班時間")}));});},[periodId]);
 const windows=availability?.windows||[];
 const saveWindows=async(submit=false)=>{const next=[...windows,windowForm].filter(w=>w.specificDate&&w.startsAt&&w.endsAt);const result=await run(()=>schedulingApi.saveAvailability(periodId,{windows:next},submit),submit?"可排班時間已提交":"草稿已儲存");if(result){setAvailability({...result,windows:next});setWindowForm({...windowForm,specificDate:"",note:""});}};
 return <div style={{padding:"20px",maxWidth:1200,margin:"0 auto"}}>
  <h1>員工排班</h1><p style={{color:"#64748b"}}>提交可排班時間、申請休假，並查看門市草稿班表。所有時間以台北時區顯示。</p>
  <div style={{display:"flex",gap:8,overflowX:"auto",marginBottom:16}}>{tabs.filter(t=>(features.staff_workday_selection_enabled||t!=="我的工作日")&&(manager||!["排班草稿","僱用資料"].includes(t))).map(t=><button key={t} style={{...button,background:tab===t?"#1d4ed8":"#e2e8f0",color:tab===t?"#fff":"#334155",whiteSpace:"nowrap"}} onClick={()=>setTab(t)}>{t}</button>)}</div>
  {tab==="我的工作日"&&features.staff_workday_selection_enabled&&<WorkdaySelectionPanel periodId={periodId} manager={manager}/>}
  {message&&<div style={{...box,background:"#eff6ff",color:"#1e40af"}}>{message}</div>}
  {tab==="我的可排班時間"&&<section style={box}><h2>我的可排班時間</h2>{(loadErrors.periods||loadErrors.availability)&&<p style={{color:"rgb(185,28,28)"}}>{loadErrors.periods||loadErrors.availability}</p>}<select style={field} value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">請選擇期間</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name}（{String(p.starts_on).slice(0,10)}～{String(p.ends_on).slice(0,10)}）</option>)}</select><p>目前狀態：{labels[availability?.status]||"尚未建立"}</p>
   <div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input type="date" style={field} value={windowForm.specificDate} onChange={e=>setWindowForm({...windowForm,specificDate:e.target.value})}/><input type="time" style={field} value={windowForm.startsAt} onChange={e=>setWindowForm({...windowForm,startsAt:e.target.value})}/><input type="time" style={field} value={windowForm.endsAt} onChange={e=>setWindowForm({...windowForm,endsAt:e.target.value})}/><select style={field} value={windowForm.preference} onChange={e=>setWindowForm({...windowForm,preference:e.target.value})}><option value="AVAILABLE">可上班</option><option value="PREFERRED">希望排班</option><option value="NOT_PREFERRED">較不希望</option></select><button style={button} onClick={()=>saveWindows(false)}>加入並儲存</button></div>
   <ul>{windows.map((w,i)=><li key={w.id||i}>{String(w.specificDate||w.specific_date).slice(0,10)}　{String(w.startsAt).slice(0,5)}～{String(w.endsAt).slice(0,5)}　{w.preference}</li>)}</ul><button style={button} disabled={!periodId} onClick={()=>saveWindows(true)}>提交本次版本</button>
  </section>}
  {tab==="休假申請"&&<><section style={box}><h2>新增休假申請</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><select style={field} value={leave.leaveType} onChange={e=>setLeave({...leave,leaveType:e.target.value})}><option value="ANNUAL">年假</option><option value="SICK">病假</option><option value="PERSONAL">事假</option><option value="STATUTORY">法定假別</option><option value="OTHER">其他</option></select><input type="datetime-local" style={field} value={leave.startsAt} onChange={e=>setLeave({...leave,startsAt:e.target.value})}/><input type="datetime-local" style={field} value={leave.endsAt} onChange={e=>setLeave({...leave,endsAt:e.target.value})}/><input style={field} placeholder="公開備註（選填）" value={leave.publicNote} onChange={e=>setLeave({...leave,publicNote:e.target.value})}/><input style={field} placeholder="私人原因（限主管）" value={leave.privateReason} onChange={e=>setLeave({...leave,privateReason:e.target.value})}/><button style={button} onClick={async()=>{if(await run(()=>schedulingApi.createTimeOff(leave),"休假申請已送出"))load();}}>送出申請</button></div></section><section style={box}><h2>{manager?"門市休假申請":"我的休假申請"}</h2>{loadErrors.timeOff&&<p style={{color:"rgb(185,28,28)"}}>{loadErrors.timeOff}</p>}{timeOff.map(r=><div key={r.id} style={{padding:"12px 0",borderBottom:"1px solid #e5e7eb"}}><b>{r.displayName}・{r.leaveType}</b>　{labels[r.status]||r.status}<div>{String(r.startsAt).replace("T"," ").slice(0,16)}～{String(r.endsAt).replace("T"," ").slice(0,16)}</div>{manager&&r.status==="PENDING"&&<div style={{display:"flex",gap:8,marginTop:8}}><button style={button} onClick={async()=>{await schedulingApi.reviewTimeOff(r.id,{status:"APPROVED"});load();}}>核准</button><button style={{...button,background:"#b91c1c"}} onClick={async()=>{await schedulingApi.reviewTimeOff(r.id,{status:"REJECTED"});load();}}>拒絕</button></div>}</div>)}</section></>}
  {tab==="排班草稿"&&manager&&<><section style={box}><h2>建立排班期間</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input style={field} placeholder="期間名稱" value={periodForm.name} onChange={e=>setPeriodForm({...periodForm,name:e.target.value})}/><input type="date" style={field} value={periodForm.startsOn} onChange={e=>setPeriodForm({...periodForm,startsOn:e.target.value})}/><input type="date" style={field} value={periodForm.endsOn} onChange={e=>setPeriodForm({...periodForm,endsOn:e.target.value})}/><button style={button} onClick={async()=>{if(await run(()=>schedulingApi.createPeriod(periodForm),"期間已建立"))load();}}>建立草稿期間</button></div></section><section style={box}><h2>草稿行事曆</h2><select style={field} value={periodId} onChange={e=>setPeriodId(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select> <button style={button} onClick={()=>run(()=>schedulingApi.seedCalendar(periodId),"已建立週一休息、平日 1 人、週末 2 人預設值")}>建立營業日預設</button> <button style={button} onClick={async()=>{const r=await run(()=>schedulingApi.createRevision(periodId,{changeReason:"手動建立草稿"}),"排班草稿已建立");if(r){const d=await schedulingApi.draft(r.id);setDraft(d);}}}>建立新版本</button>{draft&&<div><h3>第 {draft.revision.revision_no} 版</h3><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}><input type="date" style={field} value={shiftForm.shiftDate} onChange={e=>setShiftForm({...shiftForm,shiftDate:e.target.value})}/><input type="time" style={field} value={shiftForm.startsAt} onChange={e=>setShiftForm({...shiftForm,startsAt:e.target.value})}/><input type="time" style={field} value={shiftForm.endsAt} onChange={e=>setShiftForm({...shiftForm,endsAt:e.target.value})}/><input type="number" min="1" style={field} placeholder="需要人數" value={shiftForm.requiredHeadcount} onChange={e=>setShiftForm({...shiftForm,requiredHeadcount:Number(e.target.value)})}/><input style={field} placeholder="需要角色（選填）" value={shiftForm.requiredRole} onChange={e=>setShiftForm({...shiftForm,requiredRole:e.target.value})}/><button style={button} onClick={async()=>{await schedulingApi.createShift(draft.revision.id,shiftForm);setDraft(await schedulingApi.draft(draft.revision.id));}}>新增班次</button></div><select style={field} value={selectedStaff} onChange={e=>setSelectedStaff(e.target.value)}><option value="">選擇要排班的員工</option>{profiles.map(p=><option key={p.staffUserId} value={p.staffUserId}>{p.displayName}</option>)}</select>{(draft.shifts||[]).map(shift=><ShiftDraftRow key={shift.id} shift={shift} selectedStaff={selectedStaff} revisionId={draft.revision.id} onRefresh={setDraft}/>)}</div>}</section></>}
  {tab==="僱用資料"&&manager&&<section style={box}><h2>員工僱用資料</h2>{loadErrors.profiles&&<p style={{color:"rgb(185,28,28)"}}>{loadErrors.profiles}</p>}{profiles.map(p=><Profile key={p.staffUserId} profile={p} onSaved={load}/>)}</section>}
 </div>;
}
function ShiftDraftRow({shift,selectedStaff,revisionId,onRefresh}){
 const warnings=Array.isArray(shift?.warnings)?shift.warnings.filter(Boolean):[];
 const assignmentWarnings=Array.isArray(shift?.assignmentWarnings)?shift.assignmentWarnings.filter(item=>item&&item.message):[];
 return <div style={{padding:"12px 0",borderBottom:"1px solid #e5e7eb",minWidth:0}}>
  <div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><span>{String(shift.shift_date).slice(0,10)} {String(shift.starts_at).slice(0,5)}～{String(shift.ends_at).slice(0,5)}</span><button style={{...button,padding:"6px 10px"}} disabled={!selectedStaff} onClick={async()=>{await schedulingApi.assignShift(shift.id,{staffUserId:Number(selectedStaff),assignmentReason:"管理者手動排班"});onRefresh(await schedulingApi.draft(revisionId));}}>手動指派</button></div>
  {warnings.length>0&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:8,minWidth:0}}>{warnings.map((warning,index)=><strong key={`${warning}-${index}`} style={{color:"#b45309",background:"#fffbeb",border:"1px solid #fde68a",borderRadius:6,padding:"4px 8px",maxWidth:"100%",overflowWrap:"anywhere",wordBreak:"break-word"}}>⚠ {warning}</strong>)}</div>}
  {assignmentWarnings.length>0&&<div style={{marginTop:8,display:"grid",gap:6,minWidth:0}}>{assignmentWarnings.map((warning,index)=><div key={`${warning.staffUserId||"staff"}-${warning.code||"warning"}-${index}`} style={{color:warning.code==="CONTRACTED_WEEKLY_HOURS_EXCEEDED"?"#9a3412":"#92400e",background:warning.code==="CONTRACTED_WEEKLY_HOURS_EXCEEDED"?"#fff7ed":"#fffbeb",border:"1px solid #fed7aa",borderRadius:6,padding:"6px 8px",maxWidth:"100%",whiteSpace:"normal",overflowWrap:"anywhere",wordBreak:"break-word"}}><strong>{warning.displayName||"未命名員工"}</strong>：{warning.message}</div>)}</div>}
 </div>;
}

function Profile({profile,onSaved}){const [form,setForm]=useState({employmentType:profile.employmentType||"PART_TIME",hourlyRate:profile.hourlyRate||"",contractedWeeklyHours:profile.contractedWeeklyHours||"",maxWeeklyHours:profile.maxWeeklyHours||""});return <div style={{padding:"12px 0",borderBottom:"1px solid #e5e7eb"}}><b>{profile.displayName}</b><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}><select style={field} value={form.employmentType} onChange={e=>setForm({...form,employmentType:e.target.value})}>{Object.entries({FULL_TIME:"全職",PART_TIME:"兼職",CONTRACT:"契約",TEMPORARY:"臨時"}).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input style={field} type="number" placeholder="時薪" value={form.hourlyRate} onChange={e=>setForm({...form,hourlyRate:e.target.value})}/><input style={field} type="number" placeholder="契約週工時" value={form.contractedWeeklyHours} onChange={e=>setForm({...form,contractedWeeklyHours:e.target.value})}/><input style={field} type="number" placeholder="每週上限" value={form.maxWeeklyHours} onChange={e=>setForm({...form,maxWeeklyHours:e.target.value})}/><button style={button} onClick={async()=>{await schedulingApi.saveProfile(profile.staffUserId,form);onSaved();}}>儲存</button></div></div>}
