import { useEffect, useMemo, useState } from "react";
import { schedulingApi } from "../../lib/staffSchedulingApi";
import WorkdayCalendar from "./WorkdayCalendar";
import WorkdaySummaryCards from "./WorkdaySummaryCards";
import CalendarLegend from "./CalendarLegend";
import SelectedWorkdaysPanel from "./SelectedWorkdaysPanel";
import AdminWorkdayCalendar from "./AdminWorkdayCalendar";
import DailyCapacityEditor from "./DailyCapacityEditor";
import ScoreTierSettings from "./ScoreTierSettings";
import { monthKey, moveMonth } from "./calendarUtils";

export default function WorkdaySelectionPanel({periodId,manager}){
 const [month,setMonth]=useState(monthKey()),[calendar,setCalendar]=useState({days:[]}),[summary,setSummary]=useState(null),[selected,setSelected]=useState([]),[history,setHistory]=useState([]),[message,setMessage]=useState(""),[admin,setAdmin]=useState({days:[],requests:[],rules:[]}),[selectedDay,setSelectedDay]=useState(null);
 const requestLabels={DRAFT:"草稿",PENDING:"待審核",PARTIALLY_APPROVED:"部分核准",APPROVED:"已核准",REJECTED:"已拒絕",CANCELLED:"已取消"};
 const effectiveDate=`${month}-01`;
 const load=async(signal)=>{if(!periodId)return;try{const [calendarData,summaryData,historyData]=await Promise.all([schedulingApi.workdayCalendar(month,signal),schedulingApi.workdaySummary(periodId,effectiveDate,signal),schedulingApi.workdayRequests()]);setCalendar(calendarData);setSummary(summaryData);setHistory(historyData);setSelected((calendarData.days||[]).filter(day=>day.ownStatus==="DRAFT").map(day=>day.workDate));if(manager){const [adminCalendar,requests,rules]=await Promise.all([schedulingApi.adminWorkdayCalendar(month,signal),schedulingApi.adminWorkdayRequests(periodId),schedulingApi.scoreTierRules()]);setAdmin({days:adminCalendar.days,requests,rules});}}catch(error){if(error.name!=="AbortError")setMessage([error.message || "工作日月曆載入失敗", error.errorCode, error.details?.weekStart ? "週起始 " + error.details.weekStart : null].filter(Boolean).join("；"));}};
 useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[month,periodId]);
 const title=useMemo(()=>{const [year,value]=month.split("-");return `${year} 年 ${Number(value)} 月`;},[month]);
 const toggle=(date)=>setSelected(current=>current.includes(date)?current.filter(item=>item!==date):[...current,date].sort());
 const save=async()=>{try{const result=await schedulingApi.saveWorkdayDraft({periodId:Number(periodId),dates:selected,version:summary?.request?.version});setSummary(current=>({...current,request:result}));setMessage("工作日草稿已儲存");}catch(error){setMessage(error.message);}};
 const submit=async()=>{try{const result=await schedulingApi.submitWorkdayRequest({requestId:summary?.request?.id,version:summary?.request?.version});setSummary(current=>({...current,request:result}));setMessage("工作日申請已送出");await load();}catch(error){setMessage(error.message);}};
 const review=async(request,status)=>{let reason="";if(status==="REJECTED")reason=window.prompt("請輸入拒絕原因")||"";if(status==="REJECTED"&&!reason)return;await schedulingApi.reviewWorkdayRequest(request.id,{status,reason,version:request.version});await load();};
 return <section className="workday-request-page"><div className="workday-toolbar"><div><button onClick={()=>setMonth(moveMonth(month,-1))} aria-label="上個月">‹</button><button onClick={()=>setMonth(monthKey())}>今天</button><button onClick={()=>setMonth(moveMonth(month,1))} aria-label="下個月">›</button></div><h2>{title}</h2></div>{message&&<p className="workday-message" role="status">{message}</p>}<WorkdaySummaryCards summary={summary}/><CalendarLegend/><div className="workday-main"><WorkdayCalendar month={month} days={calendar.days} selected={selected} maxSelectableDays={summary?.score?.maxSelectableDays} onToggle={toggle}/><SelectedWorkdaysPanel dates={selected} onRemove={toggle} onClear={()=>setSelected([])}/></div><div className="workday-actions"><button onClick={save} disabled={!periodId||!selected.length}>儲存草稿</button><button onClick={submit} disabled={!summary?.request?.id||summary?.request?.status!=="DRAFT"}>送出申請</button></div><section><h3>申請紀錄</h3>{history.length?history.map(item=><div key={item.id}>{requestLabels[item.status]||item.status}・第 {item.revision_no||item.revisionNo||1} 版</div>):<p>尚無申請紀錄。</p>}</section>{manager&&<section className="workday-admin"><h2>管理員工作日申請管理</h2><AdminWorkdayCalendar days={admin.days} requests={admin.requests} onReview={review} onSelectDay={setSelectedDay}/><DailyCapacityEditor day={selectedDay} onSave={async input=>{await schedulingApi.updateDateCapacity(input.workDate,{maxRequestCapacity:input.maxRequestCapacity,isLocked:input.isLocked,deadline:input.deadline,pendingReservesCapacity:false,adminAssignmentCountsTowardLimit:true,version:input.version,reason:input.reason});await load();}}/><ScoreTierSettings rules={admin.rules} onSave={()=>setMessage("級距編輯 API 已就緒；請由管理設定表單輸入完整生效區間與原因。")}/><div className="workday-settings"><h3>員工每週上限覆寫</h3><p>需填員工、有效日期、天數與原因；API 已建立，未建立虛構分數。</p></div></section>}</section>;
}
